### ISSUE TITLE
"Relax"

### ISSUE THREAD

**Issue by ghost** [JMSS-Unknown/JMSS-Unknown.github.io#4]
Just because there are no more periods in the day doesn't mean we get to relax. I and many others have homework to do after school which is not at all relaxing. 

If you could just get rid of the "Relax" and replace it with the better fitting subtitle "No periods left today".

**Comment by JMSS-Unknown** [comment]
I do not want to replace the main text with "No periods left today" as the text is too long and would not fit into the design of the site. I want all the text to fit over the horizontal bar. If I extended the bar, then it will look out of place when the actual timer is showing.
